version: '3'
services:
    node:
        build:
            context: ./Node_Express
            dockerfile: Dockerfile
        image: k6_node
        restart: unless-stopped
        tty: true
        ports:
            - "8001:8080"
        networks:
            - k6tests
    app:
        build:
            context: ./docker/app
            dockerfile: Dockerfile
        image: k6_laravel_app
        restart: unless-stopped
        tty: true
        ports:
            - "6001:6001"
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www/html
        volumes:
            - ./PHP_Laravel:/var/www/html
            - ./tmp:/tmp
        networks:
            - k6tests
    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        image: k6_laravel_nginx
        restart: unless-stopped
        tty: true
        depends_on:
            - app
        ports:
            - "8080:80"
            - "443:443"
        volumes:
            - "./PHP_Laravel/public:/var/www/html/public:ro"
            - "./PHP_Laravel/storage:/var/www/html/storage:ro"
        networks:
            - k6tests
    mysql:
        image: 'mysql/mysql-server:8.0'
        restart: unless-stopped
        ports:
            - '${FORWARD_DB_PORT:-8001}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'k6-mysql:/var/lib/mysql'
        networks:
            - k6tests
       
    adminer:
        image: 'adminer:latest'
        restart: unless-stopped
        ports:
            - 8003:8080
        environment:
            MYSQL_USERNAME: "${DB_USERNAME}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            PMA_HOST: mysql
        depends_on:
            - mysql
        networks:
            - k6tests

networks:
    k6tests:
        driver: bridge
volumes:
    k6-mysql:
        driver: local
